### ISSUE TITLE
diagonal Line through circle on IOS

### ISSUE THREAD

**Issue by stokesbga** [prscX/react-native-app-tour#26]
Im seeing a diagonal thin line on ios. I set my targetCircleColor to #00000000 if it matters

<img width="127" alt="screen shot 2018-06-20 at 9 58 47 pm" src="https://user-images.githubusercontent.com/8782370/41693811-1b2fcc1e-74d5-11e8-9361-c9c026a121da.png">

**Comment by prscX** [comment]
Thanks @stokesbga for raising the issue. Looks like it is a native library issue.

Can you please raise your issue to [aromajoin/material-showcase-ios](https://github.com/aromajoin/material-showcase-ios)

Thanks
</ Pranav >

**Comment by prscX** [comment]
[ISSUE:60](https://github.com/aromajoin/material-showcase-ios/issues/60)

Thanks
</ Pranav >

**Comment by quangctkm9207** [comment]
It happens in [the native library](https://github.com/aromajoin/material-showcase-ios).
I am sorry for a late update.
It is fixed in the latest version (0.6.2). Please check it out.

**Comment by prscX** [comment]
Thanks a lot @quangctkm9207 for sharing the update and effort.

I will update library and push a release with the same.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @stokesbga, I have upgraded library to latest iOS native library for the fix. 

Can you please install latest version and verify the same. Please let us know in case you still face the same issue.

[v0.0.16](https://github.com/prscX/react-native-app-tour/releases/tag/v0.0.16)

Thanks
</ Pranav >
