### ISSUE TITLE
does not install MaterialShowcase (0.6.4)

### ISSUE THREAD

**Issue by sajadweb** [prscX/react-native-app-tour#57]
After react-native link react-native-app-tour, please verify node_modules/react-native-app-tour/ios/ contains Pods folder. If does not exist please execute pod install command on node_modules/react-native-app-tour/ios/, if any error => try pod repo update then pod install

_> pod install
Analyzing dependencies
Downloading dependencies
Installing MaterialShowcase (0.6.4)
[!] Unable to determine Swift version for the following pods:

- `MaterialShowcase` does not specify a Swift version and none of the targets (`RNAppTour`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

[!] The Podfile contains framework or static library targets (RNAppTour), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).

**Comment by prscX** [comment]
Thanks @sajabweb for raising the issue. Could you share you installed cocoapod version, please?

Thanks 
</ Pranav >

**Comment by sajadweb** [comment]
hi @prscX 
pod --version
1.6.0.beta.2

**Comment by dgruseck** [comment]
For me it works with cocoapods 1.5.3 but not with anything that is newer than that.
Tested with every version till 1.7.0.beta.1.

**Comment by prscX** [comment]
Thanks @dgruseck for sharing your findings. Personally, I have not tested with the latest cocoapod version. Please give me some time, I will get back to you with the fix.

Thanks
</ Pranav >

**Comment by blntylmn** [comment]
Use cocoapods 1.5.3
`sudo gem uninstall cocoapods`
``sudo gem install cocoapods` -v 1.5.3`
`pod install`

and follow the step on this video [https://www.youtube.com/watch?v=iBjsCrEtYW4&feature=youtu.be](url) or main page of this repo in Getting started > IOS section

After this some of my pods (I use a lot :)) doesn't like this cocoapods version (1.5.3) especially (I guess) `react-native-fbsdk`. So I had to install latest stable version of cocoapods again which is at the moment `1.6.1`
`sudo gem install cocoapods`
and go into my projects ios folder
`cd ios`
`rm -rf Pods`
`rm -rf Podfile.lock`
`rm -rf build`
`pod install`
`cd ..`
`react-native run-ios`
BUILD SUCCEDED and everything works as expected :)
Except :( annoying YellowBox says
`Module RNAppTour requires main queue setup since it overrides init but doesn't implementw requiresMainQueueSetup`
So I had to add at line arround 80
`+ (BOOL)requiresMainQueueSetup
{
  return YES;
}` in 
`node_modules/react-native-app-tour/ios/RNAppTour.m`
(@prscX add this to the master please that warning is so annoying)
cd out to till the root of project with
`cd ..`
run `react-native run-ios` again
BUILD SUCCEDED and no warnings at this time :)

**Comment by ustincameron** [comment]
Downgrading cocoapods is not a real solution. I wrote to you @prscX yesterday about a different component, but this one has the exact same issue. Pod install fails and no swift version. All your components atm end up breaking the build. Can you update the readme's?

**Comment by LuisBonsembiante** [comment]
Hi everyone any news about that or the project is close?..thanks in advance for de response

**Comment by prscX** [comment]
@LuisBonsembiante: I need to look into using latest Cocoapods. Meantime, if you get fix please feel free to share PR for the same.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi: I have fixed the pods installation issue. Could you please download latest released version and verify the same.

Please let me know in case you till face the same issue.

Thanks
</ Pranav >

**Comment by ravifullestop** [comment]
We are getting issue still in it. The project is not even building.
